### ISSUE TITLE
Dependency on help2man

### ISSUE THREAD

**Issue by leahneukirchen** [rrthomas/mmv#10]
Build fails when help2man is not found:

```
  GEN      mmv.1
./build-aux/missing: line 81: --no-info: command not found
WARNING: '--no-info' is missing on your system.
         You might have modified some files without having the proper
         tools for further handling them.  Check the 'README' file, it
         often tells you about the needed prerequisites for installing
         this package.  You may also peek at any GNU archive site, in
         case some other package contains this missing '--no-info' program.
```

But the mmv.1 is included in release tarballs already, so help2man shouldn't be required.

**Comment by rrthomas** [comment]
Unfortunately, without more complicated make rules that isn't going to work, since `mmv.1` depends on `mmv`, which isn't in the tarball, and will be newer than `mmv.1` as soon as it's built. I guess I shouldn't ship `mmv.1` in the tarball, so I'll fix that.

The instructions in `README.md` already note that `help2man` is needed to build from source.

**Comment by leahneukirchen** [comment]
This makes cross compiling a lot harder then. :(

**Comment by rrthomas** [comment]
I hear ya, ima sort this out.

**Comment by rrthomas** [comment]
I have attempted to fix things so that `help2man` is not run when cross-compiling.

**Comment by rrthomas** [comment]
Hmm, maybe it would be better simply to make `help2man` default to `touch`.

**Comment by leahneukirchen** [comment]
lgtm.

**Comment by rrthomas** [comment]
Sorry, since I was chopping and changing so much, please can you confirm the latest version is OK (or not) @leahneukirchen?

**Comment by leahneukirchen** [comment]
yes, using touch is fine. thanks!

**Comment by rrthomas** [comment]
Many thanks for reporting this and then being patient. I'll make a new release shortly.

**Comment by rrthomas** [comment]
2.3 now released.

**Comment by rrthomas** [comment]
I have found a less hacky solution to this which I will shortly release. If you'd like to check git HEAD still works for you, that would be great.
