### ISSUE TITLE
Error on bdw-gc trying to compile from source

### ISSUE THREAD

**Issue by AgilentGCMS** [rrthomas/mmv#14]
Hello,

I am trying to compile mmv on a Red Hat Enterprise box. I cloned the git repository, did `./bootstrap`, then tried `./configure`. That step failed with
```
./configure: line 29039: syntax error near unexpected token `BDW_GC,bdw-gc'
./configure: line 29039: `PKG_CHECK_MODULES(BDW_GC,bdw-gc >= 7.2)'
```
No idea what this error is or how to get past it. Help?

**Comment by rrthomas** [comment]
You need `pkg-config` installed; sorry, it seems that this is missing from the requirements list. I'll fix that.

**Comment by rrthomas** [comment]
I fixed it. I didn't think this warranted a new release, but it'll be in there next time I make a release.
