### ISSUE TITLE
Manpage mentions mystery '-k' option

### ISSUE THREAD

**Issue by ferdnyc** [rrthomas/mmv#17]
The man page, at one point, says (right after the list of "task option choices"):

> Only one of these option may be given, and it applies to all matching files.  Remaining options need not be given separately, i.e. "mmv  -mk" is allowed.

...But there is no '-k' option. If there ever _was_, it was already removed by the time the sources were imported in fd1dcea. So, `mmv -mk` and/or `mmv -m -k` doesn't make any sense.

**Comment by rrthomas** [comment]
This text was removed 3 years ago in be731b0.

**Comment by ferdnyc** [comment]
@rrthomas My mistake, so it was! Wow, Fedora's mmv is _really_ out of date. I'll try and prod them to update to a version that's not from 2016.

**Comment by JensKuehnel** [comment]
@ferdnyc You don't need to do that. I already did. But because it removed the mad command I could not push it stable Fedora 38/39. Now with 2.6 and mad readded I will push it to F38/39 as well as EPEL8+9 in the next couple of days.

**Comment by JensKuehnel** [comment]
F39:   https://bodhi.fedoraproject.org/updates/FEDORA-2024-7f15b737d8
F38:   https://bodhi.fedoraproject.org/updates/FEDORA-2024-c97475d030
are ready for testing.
EPEL8+9 will take some more time.

**Comment by rrthomas** [comment]
@JensKuehnel forgive me if I overlooked something, but as upstream it would be useful to have the feedback that removing a feature makes a distro decide not to upgrade. I reintroduced the feature because of user feedback.

**Comment by JensKuehnel** [comment]
@rrthomas Sorry, should have told you. But we had a working version from the debian source  which worked fine and for Fedora 40 it would have switch to your fork anyway.

P.S.: EPEL8+EPEL9 is on the way to release as well.
