### ISSUE TITLE
One-liner to append + concatenate?

### ISSUE THREAD

**Issue by Geremia** [rrthomas/mmv#21]
@rrthomas Is there a way to append a file to each of the matched files and then concatenate all those files, all in one line?

I know the following command doesn't work (due to there being 3 args), but I am trying to do something like this:

    mad appendix \*.txt concatenated.txt

where `appendix.txt` is appended to all the `*.txt` files and those files (each with `appendix.txt` appended to them) are concatenated into one large `concatenated.txt`?

**Comment by rrthomas** [comment]
Can't think of one, sorry. Doesn't seem like a big deal to me, since you can use `cat` on the result of `mad`; is there some reason to want a single command?

**Comment by Geremia** [comment]
@Geremia Primarily speed. I have hundreds of thousands of files that I'd like to append to. Piping into `cat` would slow things down.

**Comment by rrthomas** [comment]
If you're appending many thousands of files, how is using `cat` going to be slow?

Adding padding: isn't that just another use of `mad`?

**Comment by Geremia** [comment]
@rrthomas `mad appendix.txt *.txt` doesn't work (>2 args), and `mad appendix.txt \*.txt` simply creates a file named `*.txt` whose contents are `appendix.txt`. Am I missing something?

**Comment by rrthomas** [comment]
> @rrthomas `mad appendix.txt *.txt` doesn't work (>2 args), and `mad appendix.txt \*.txt` simply creates a file named `*.txt` whose contents are `appendix.txt`. Am I missing something?

Sorry, indeed that won't work: you can append multiple sources to one target (so you can use `mad` instead of `cat`) but you can't append a single source to multiple targets (so you can't use `mad` to add the appendix to lots of files).

**Comment by Geremia** [comment]
@rrthomas 

```
--- mmv.c	2024-06-18 16:58:34.436285606 -0700
+++ mmv.c	2024-06-18 16:58:04.511294635 -0700
@@ -1570,6 +1570,8 @@
 	else
 		while ((k = read(f, buf, BUFSIZ)) > 0 && write(t, buf, (size_t)k) == k)
 			;
+        char null_byte = 0x00;
+        write(t, &null_byte, 1);
 	if (!(op & (APPEND | OVERWRITE)))
 		if (
 			stat(pathbuf, &fstat) ||

```
achieved what I was looking for.
