### ISSUE TITLE
mmv fails to move directories

### ISSUE THREAD

**Issue by milahu** [rrthomas/mmv#24]
currently `mmv` can only move files, but not directories

```sh
cd $(mktemp -d)

mkdir -p a/b

find *
# a
# a/b

mmv "*/*" "#1-2/#2"
# a/b -> a-2/b : target directory does not exist.
# Nothing done.

find *
# a
# a/b

mmv --makedirs "*/*" "#1-2/#2"
# a/b -> a-2/b has failed.
# The following left undone:
# a/b -> a-2/b

find *
# a
# a/b
# a-2
```

> target directory does not exist

nitpick: `mmv` should recommend adding the `--makedirs` flag

**Comment by rrthomas** [comment]
Thanks for the report. Something odd is happening here:

```sh
$ mkdir -p a/b
$ mmv -D --verbose "*/*" "#1-2/#2"
creating directory a-2/
a/b -> a-2/b has failed.
The following left undone:
a/b -> a-2/b
$ find *
a
a/b
a-2
$ mmv -D --verbose "*/*" "#1-2/#2"
a/b -> a-2/b : done
$ find *
a
a-2
a-2/b
```

Looks like the fact that `a-2` doesn't exist first time round influences the move even though it seems that the directory has been created by the time the move is attempted.

**Comment by rrthomas** [comment]
> nitpick: `mmv` should recommend adding the `--makedirs` flag

Good idea, please file a separate issue for this.

**Comment by rrthomas** [comment]
Yes, mmv is incorrectly deciding that a cross-device move is needed, having not updated the destination's `DIRINFO` after creating the directory.

**Comment by milahu** [comment]
thanks for the quick fix : )
