### ISSUE TITLE
2.9: broken description in the mmv.1 man page

### ISSUE THREAD

**Issue by hhoffstaette** [rrthomas/mmv#26]
I just updated to 2.9 and found that apparently something went wrong during the release process.
The pre-generated `mmv.1` man page contains an error message:

...
.SH DESCRIPTION
**\&./build\-aux/mmv\-help2man\-wrapper: 6: ./mmv: Permission denied**
...

Out of curiosity I installed gengetopt, ran bootstrap/configure/make and the generated man page looks fine again.

Thanks for mmv! :heart:

**Comment by rrthomas** [comment]
Many thanks for letting me know, I have released 2.9.1 which fixes this problem.
