### ISSUE TITLE
Was anything lost

### ISSUE THREAD

**Issue by eyexpo-thomas** [rrthomas/mmv#5]
What does Vladimir mean when he writes:

> I do not have in hand either the full GPL text or the source code of the last mmv release (oops)

here: https://launchpad.net/debian/squeeze/+source/mmv/+copyright

Did we lose some of the source code from that release, or am I misunderstanding it?

**Comment by rrthomas** [comment]
I don't think anything was lost. However, although I have used mmv for many years, I have only just become its maintainer, so I don't have first-hand knowledge of the history.

mmv was added to Debian in 1996. Vladimir was not reached to relicense mmv until 1998, so his comment that he doesn't have the source code from the last release presumably dates from 1998. As far as I can see, the original Debian maintainer must have obtained the sources from Usenet.

So, assuming Vladimir already didn't have the sources over 20 years ago, the best thing for someone interested in them would be to consult a Usenet archive. I started my repo with the sources as of Debian package version 1.01b-19, that is to say, with the Debian patches already applied.
