### ISSUE TITLE
Use of gc

### ISSUE THREAD

**Issue by leahneukirchen** [rrthomas/mmv#9]
Is it really reasonable to use Boehm GC for a tool like this? It runs as one-shot only, so you could just leak the memory instead.

**Comment by rrthomas** [comment]
A little history (in case you don't know it): mmv used to have a simple custom allocator. I removed it, and couldn't work out the object lifetimes, so decided to use libgc (a technique I've used in the past). You're probably right about the one-shotness (the thought had occurred to me), but using libgc is more fun, I don't have to care whether leaking would be a problem or not, and ASAN doesn't complain.

I am not aware of the use of libgc causing any problems…?

**Comment by leahneukirchen** [comment]
It's just a library many systems don't necessarily have installed (here it's used only by inkscape, guile, w3m, zile...).

**Comment by rrthomas** [comment]
That's true, but it doesn't sound serious. (I'm responsible for Zile needing it; recent releases of Zile are written in Vala and don't need it.)

**Comment by rrthomas** [comment]
Closing, since this doesn't seem to be a problem.
